# Generated by Django 5.1.3 on 2024-12-12 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('pinyin', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('plane_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('first_class_seats', models.IntegerField()),
                ('business_seats', models.IntegerField()),
                ('economy_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('airport_code_3', models.CharField(max_length=3)),
                ('airport_name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='flight.city')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.IntegerField(primary_key=True, serialize=False)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('remaining_first_class_seats', models.IntegerField()),
                ('remaining_business_seats', models.IntegerField()),
                ('remaining_economy_seats', models.IntegerField()),
                ('distance', models.FloatField()),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_airport', to='flight.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_airport', to='flight.airport')),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plane', to='flight.plane')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending', max_length=20)),
                ('total_price', models.FloatField()),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='account.passenger')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='flight.ticket')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
