# Generated by Django 5.1.3 on 2024-12-14 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_passenger_options_alter_user_options_and_more'),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': '证件', 'verbose_name_plural': '证件管理'},
        ),
        migrations.AlterField(
            model_name='document',
            name='document_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='证件ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='证件号'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('id_card', '身份证'), ('passport', '护照'), ('hukou booklet', '户口簿'), ('birth certificate', '出生证明'), ('other', '其他')], max_length=50, verbose_name='证件类型'),
        ),
        migrations.AlterField(
            model_name='document',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='account.passenger', verbose_name='乘客'),
        ),
    ]
