# Generated by Django 5.1.3 on 2024-12-05 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Lv 1'), (2, 'Lv 2'), (3, 'Lv 3'), (4, 'Lv 4'), (5, 'Lv 5'), (6, 'Lv 6'), (7, '银卡'), (8, '金卡'), (9, '白金卡')], default=1)),
                ('require_miles', models.IntegerField()),
                ('require_tickets', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='level.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
