# Generated by Django 5.1.3 on 2024-12-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Lv 1'), (2, 'Lv 2'), (3, 'Lv 3'), (4, 'Lv 4'), (5, 'Lv 5'), (6, 'Lv 6'), (7, '银卡'), (8, '金卡'), (9, '白金卡')], default=1)),
                ('require_miles', models.IntegerField()),
                ('require_tickets', models.IntegerField()),
            ],
        ),
    ]
