# Generated by Django 5.1.3 on 2024-12-14 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': '会员等级', 'verbose_name_plural': '会员等级管理'},
        ),
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.IntegerField(choices=[(1, 'Lv 1'), (2, 'Lv 2'), (3, 'Lv 3'), (4, 'Lv 4'), (5, 'Lv 5'), (6, 'Lv 6'), (7, '银卡'), (8, '金卡'), (9, '白金卡')], default=1, verbose_name='会员等级'),
        ),
        migrations.AlterField(
            model_name='level',
            name='require_miles',
            field=models.IntegerField(verbose_name='所需里程'),
        ),
        migrations.AlterField(
            model_name='level',
            name='require_tickets',
            field=models.IntegerField(verbose_name='所需购票次数'),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='活动名称')),
                ('description', models.TextField(verbose_name='活动描述')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='level.level', verbose_name='适用等级')),
            ],
            options={
                'verbose_name': '优惠活动',
                'verbose_name_plural': '优惠活动管理',
            },
        ),
    ]
