# Generated by Django 5.1.3 on 2024-12-06 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0002_alter_userlevel_level_alter_userlevel_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLevel',
        ),
    ]
