# Generated by Django 5.1.3 on 2024-12-12 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.BooleanField(choices=[(True, 'Male'), (False, 'Female')])),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('person_type', models.CharField(choices=[('adult', 'Adult'), ('student', 'Student'), ('teacher', 'Teacher'), ('senior', 'Senior Citizen')], default='adult', max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Passenger',
                'verbose_name_plural': 'Passengers',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(max_length=255)),
                ('accumulated_miles', models.FloatField(default=0)),
                ('ticked_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('digital', 'Digital Invoice'), ('paper', 'Paper Invoice')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('identification_number', models.CharField(blank=True, max_length=50, null=True)),
                ('company_address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_account', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserPassengerRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='account.passenger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='account.user')),
            ],
            options={
                'unique_together': {('user', 'passenger')},
            },
        ),
    ]
